---
  - name: "install dependencies and configure docker"
    hosts: localhost
    connection: local
    become: true
    tasks:

    - name: Install a list of packages
      apt:
        pkg:
          - docker-ce
          - python-pip
          - git
          - python3-pip
        state: latest
        update_cache: true

    - name: install bs4
      command: python3 -m pip install bs4

    - name: Install docker pip package
      pip:
        name: docker-py
        state: present

    - name: Start and enable docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: build docker image
      command: docker build -t nginx-local -f /usr/local/dev/config/Dockerfile .

    - name: run docker image
      command: docker run --name nginx-local -p 80:8080 -d --restart unless-stopped nginx-local
      # TODO: would have liked to get the hardening role to work leaving this out for lack of time , weird ansible issues.
      #roles:
      # - Ubuntu1804-CIS
